export const homeObjOne = {
    id: 'about',
    lightBg: true,
    lightText: false,
    LightTextDesc: true,
    topLine: 'ABOUT ',
    headLine: 'cartier',
    description: 'Cartier is a French luxury goods conglomerate which designs, manufactures, distributes, and sells jewellery, leather goods and watches.It is regarded as one of the most prestigious jewellery manufacturers in the world.',
    buttonLabel: 'Discover more',
    imgStart: false,
    img: 'pics/img1.jpg',
    alt: 'cartier',
    dark: true,
    primary: true,
    darkText: true,  
};

export const homeObjTwo = {
    id: 'products',
    lightBg: false,
    lightText: true,
    LightTextDesc: true,
    topLine: 'Products ',
    headLine: 'watches',
    description: 'Browse the ultimate selection of authentic Cartier watches online. Uncover incredible deals from local and international sellers.',
    buttonLabel: 'Get started',
    imgStart: true,
    img: 'pics/img2.jpg',
    alt: 'cartier',
    dark: true,
    primary: true,
    darkText: false,  
};

export const homeObjThree = {
    id: 'branches',
    lightBg: true,
    lightText: false,
    LightTextDesc: true,
    topLine: 'Branches ',
    headLine: 'Stores',
    description: 'Cartier operates more than 200 stores in 125 countries, with three Temples (Historical Maisons) in London, New York, and Paris. ',
    buttonLabel: 'Details',
    imgStart: false,
    img: 'pics/img3.png',
    alt: 'cartier branches',
    dark: true,
    primary: true,
    darkText: true,  
};

export const homeObjFour = {
    id: 'sign up',
    lightBg: false,
    lightText: true,
    LightTextDesc: true,
    topLine: 'Join our team ',
    headLine: 'Creating an account is extremely easy',
    description: 'Get everything set up and ready in under 10 minutes.All you need to add your information .',
    buttonLabel: 'Sign up',
    imgStart: true,
    img: 'pics/img4.svg',
    alt: 'cartier',
    dark: true,
    primary: true,
    darkText: false,  
};